version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: redesocial
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend-auth:
    build: ./backend-auth
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/redesocial
    ports:
      - "3001:3000"

  backend-posts:
    build: ./backend-posts
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/redesocial
    ports:
      - "3002:3000"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend-auth
      - backend-posts

volumes:
  db_data: